// Golden-fixture tests — fixtures generated by Python replicas of the old
// app's pandas/numpy formulas (see docs/IMPLEMENTATION_LOG.md, M2).
import { describe, expect, it } from "vitest";
import golden from "./__fixtures__/golden.json";
import { wilson } from "./wilson";
import { winType } from "./winType";
import { impliedProb, fairProbs } from "./moneyline";
import { gradeModelProb, blendProbs } from "./probBlend";
import { edgeComposite, meanLastN, slopeLastN, EDGE_SCALE } from "./edgeComposite";
import { parseGameId, opponentLabel } from "./gameId";
import { squashRatio, mismatchScore, mismatchEdge } from "./ranks";

const close = (a: number, b: number) => expect(a).toBeCloseTo(b, 10);

describe("wilson", () => {
  for (const c of golden.wilson) {
    it(`p=${c.p} n=${c.n}`, () => {
      const w = wilson(c.p, c.n);
      close(w.center, c.center);
      close(w.low, c.low);
      close(w.high, c.high);
    });
  }
});

describe("winType", () => {
  for (const c of golden.winType) {
    it(`${c.homeScore}-${c.awayScore} @ ${c.spread}`, () => {
      expect(winType(c.homeScore, c.awayScore, c.spread)).toBe(c.expected);
    });
  }
});

describe("moneyline", () => {
  for (const c of golden.moneyline) {
    it(`${c.awayMl}/${c.homeMl}`, () => {
      close(impliedProb(c.awayMl)!, c.awayImplied);
      close(impliedProb(c.homeMl)!, c.homeImplied);
      const f = fairProbs(c.awayMl, c.homeMl);
      close(f.awayFair!, c.awayFair);
      close(f.homeFair!, c.homeFair);
      close(f.overround!, c.overround);
    });
  }
});

describe("gradeModelProb + blend", () => {
  for (const c of golden.gradeModel) {
    it(`${c.gradeAway} vs ${c.gradeHome}`, () => {
      const p = gradeModelProb(c.gradeAway, c.gradeHome)!;
      close(p, c.pAway);
      // blend of market p_home=0.6 with model p_home=(1-pAway)
      close(blendProbs(0.6, 1 - p)!, c.blendWithMarket0_6);
    });
  }
  it("falls back when one side missing", () => {
    expect(blendProbs(0.7, null)).toBe(0.7);
    expect(blendProbs(null, 0.3)).toBe(0.3);
    expect(blendProbs(null, null)).toBeNull();
  });
});

describe("slopeLastN / meanLastN (numpy polyfit parity)", () => {
  for (const [i, c] of golden.slopes.entries()) {
    it(`series ${i}`, () => {
      close(slopeLastN(c.values, c.n)!, c.slope);
      close(meanLastN(c.values, 3)!, c.meanLast3);
    });
  }
});

describe("edgeComposite", () => {
  for (const c of golden.edgeComposite) {
    it(`grades ${c.gradeAway}/${c.gradeHome}`, () => {
      const r = edgeComposite(
        { grade: c.gradeAway, ...c.away },
        { grade: c.gradeHome, ...c.home },
      );
      close(r.edge, c.edge);
      close(r.pAway, c.pAway);
      close(r.pAway, 1 / (1 + Math.exp(-EDGE_SCALE * c.edge)));
    });
  }
});

describe("spread buckets (grid-aligned)", () => {
  // mirrors the bucketOf helpers used by SpreadWinPct / previews engine
  const bucket = (v: number, bs: number) => {
    const lo = Math.floor(v / bs + 1e-9) * bs;
    const frac = Math.abs(bs - Math.round(bs)) > 1e-9;
    const fmt = (x: number) => (frac ? x.toFixed(1) : String(Math.round(x)));
    return { label: `${fmt(lo)} to ${fmt(lo + bs)}`, lo };
  };
  for (const c of golden.spreadBuckets) {
    it(`${c.value} @ ${c.binSize}`, () => {
      const b = bucket(c.value, c.binSize);
      expect(b.label).toBe(c.label);
      close(b.lo, c.lo);
    });
  }
});

describe("gameId", () => {
  it("parses valid ids", () => {
    expect(parseGameId("2024_05_DAL_SF")).toEqual({ season: 2024, week: 5, away: "DAL", home: "SF" });
    expect(opponentLabel("2024_05_DAL_SF", "DAL")).toBe("@SF");
    expect(opponentLabel("2024_05_DAL_SF", "SF")).toBe("DAL");
  });
  it("rejects malformed ids (deviation #2)", () => {
    expect(parseGameId("garbage")).toBeNull();
    expect(opponentLabel("garbage", "SF")).toBe("—");
    expect(parseGameId(null)).toBeNull();
  });
});

describe("ranks helpers", () => {
  it("squashRatio compresses toward 0.5", () => {
    close(squashRatio(1), 0.75);
    close(squashRatio(0), 0.25);
    close(squashRatio(0.5), 0.5);
  });
  for (const c of golden.ranks) {
    it(`off=${c.offRank} def=${c.defAllowedRank}`, () => {
      expect(mismatchScore(c.offRank, c.defAllowedRank)).toBe(c.score);
      expect(mismatchEdge(c.offRank, c.defAllowedRank, c.maxRank)).toBe(c.edge);
    });
  }
});

// ---- Session-5 models: Elo + Pythagorean (hand-computed cases, not golden fixtures) ----
import { buildEloIndex, eloPHome, eloMovMultiplier, ELO_INIT, ELO_K, ELO_HFA } from "./elo";
import { pythWinPct, log5 } from "./pythagorean";

describe("elo", () => {
  it("equal ratings favor home by HFA", () => {
    // 1/(1+10^(-48/400)) = 0.5686...
    close(eloPHome(1505, 1505), 1 / (1 + Math.pow(10, -48 / 400)));
  });
  it("mov multiplier at margin 7, even matchup", () => {
    close(eloMovMultiplier(7, 0), Math.log(8) * (2.2 / 2.2));
  });
  it("single game updates ratings symmetrically and pre-game entry is unshifted", () => {
    const idx = buildEloIndex([
      { gameId: "g1", season: 2020, awayTeam: "A", homeTeam: "B", awayScore: 10, homeScore: 24, order: 1 },
      { gameId: "g2", season: 2020, awayTeam: "B", homeTeam: "A", awayScore: null, homeScore: null, order: 2 },
    ]);
    const e1 = idx.get("g1")!;
    close(e1.eloAway, ELO_INIT);
    close(e1.eloHome, ELO_INIT);
    const pHome = eloPHome(ELO_INIT, ELO_INIT);
    close(e1.pHome, pHome);
    // home won by 14: delta = K * mov * (1 - pHome)
    const mov = eloMovMultiplier(14, ELO_HFA); // winner diff = eh + HFA - ea = 48
    const delta = ELO_K * mov * (1 - pHome);
    const e2 = idx.get("g2")!;
    // g2: B (winner) is away, A is home
    close(e2.eloAway, ELO_INIT + delta);
    close(e2.eloHome, ELO_INIT - delta);
  });
  it("season change regresses toward the mean", () => {
    const idx = buildEloIndex([
      { gameId: "g1", season: 2020, awayTeam: "A", homeTeam: "B", awayScore: 0, homeScore: 30, order: 1 },
      { gameId: "g2", season: 2021, awayTeam: "A", homeTeam: "B", awayScore: null, homeScore: null, order: 2 },
    ]);
    const pHome = eloPHome(ELO_INIT, ELO_INIT);
    const delta = ELO_K * eloMovMultiplier(30, ELO_HFA) * (1 - pHome);
    const e2 = idx.get("g2")!;
    close(e2.eloHome, (ELO_INIT + delta) * (2 / 3) + ELO_INIT * (1 / 3));
    close(e2.eloAway, (ELO_INIT - delta) * (2 / 3) + ELO_INIT * (1 / 3));
  });
});

describe("pythagorean", () => {
  it("equal points = 50%", () => close(pythWinPct(300, 300)!, 0.5));
  it("DAL-like 471/512", () => {
    const p = pythWinPct(471, 512)!;
    close(p, Math.pow(471, 2.37) / (Math.pow(471, 2.37) + Math.pow(512, 2.37)));
    expect(p).toBeLessThan(0.5);
  });
  it("log5 symmetry and identity", () => {
    close(log5(0.5, 0.5)!, 0.5);
    close(log5(0.7, 0.3)!, 1 - log5(0.3, 0.7)!);
    // log5(0.7, 0.3) = (0.7*0.7)/(0.7*0.7 + 0.3*0.3)
    close(log5(0.7, 0.3)!, 0.49 / (0.49 + 0.09));
  });
});
