// Golden-fixture tests — fixtures generated by Python replicas of the old
// app's pandas/numpy formulas (see docs/IMPLEMENTATION_LOG.md, M2).
import { describe, expect, it } from "vitest";
import golden from "./__fixtures__/golden.json";
import { wilson } from "./wilson";
import { winType } from "./winType";
import { impliedProb, fairProbs } from "./moneyline";
import { gradeModelProb, blendProbs } from "./probBlend";
import { edgeComposite, meanLastN, slopeLastN, EDGE_SCALE } from "./edgeComposite";
import { parseGameId, opponentLabel } from "./gameId";
import { squashRatio, mismatchScore, mismatchEdge } from "./ranks";

const close = (a: number, b: number) => expect(a).toBeCloseTo(b, 10);

describe("wilson", () => {
  for (const c of golden.wilson) {
    it(`p=${c.p} n=${c.n}`, () => {
      const w = wilson(c.p, c.n);
      close(w.center, c.center);
      close(w.low, c.low);
      close(w.high, c.high);
    });
  }
});

describe("winType", () => {
  for (const c of golden.winType) {
    it(`${c.homeScore}-${c.awayScore} @ ${c.spread}`, () => {
      expect(winType(c.homeScore, c.awayScore, c.spread)).toBe(c.expected);
    });
  }
});

describe("moneyline", () => {
  for (const c of golden.moneyline) {
    it(`${c.awayMl}/${c.homeMl}`, () => {
      close(impliedProb(c.awayMl)!, c.awayImplied);
      close(impliedProb(c.homeMl)!, c.homeImplied);
      const f = fairProbs(c.awayMl, c.homeMl);
      close(f.awayFair!, c.awayFair);
      close(f.homeFair!, c.homeFair);
      close(f.overround!, c.overround);
    });
  }
});

describe("gradeModelProb + blend", () => {
  for (const c of golden.gradeModel) {
    it(`${c.gradeAway} vs ${c.gradeHome}`, () => {
      const p = gradeModelProb(c.gradeAway, c.gradeHome)!;
      close(p, c.pAway);
      // blend of market p_home=0.6 with model p_home=(1-pAway)
      close(blendProbs(0.6, 1 - p)!, c.blendWithMarket0_6);
    });
  }
  it("falls back when one side missing", () => {
    expect(blendProbs(0.7, null)).toBe(0.7);
    expect(blendProbs(null, 0.3)).toBe(0.3);
    expect(blendProbs(null, null)).toBeNull();
  });
});

describe("slopeLastN / meanLastN (numpy polyfit parity)", () => {
  for (const [i, c] of golden.slopes.entries()) {
    it(`series ${i}`, () => {
      close(slopeLastN(c.values, c.n)!, c.slope);
      close(meanLastN(c.values, 3)!, c.meanLast3);
    });
  }
});

describe("edgeComposite", () => {
  for (const c of golden.edgeComposite) {
    it(`grades ${c.gradeAway}/${c.gradeHome}`, () => {
      const r = edgeComposite(
        { grade: c.gradeAway, ...c.away },
        { grade: c.gradeHome, ...c.home },
      );
      close(r.edge, c.edge);
      close(r.pAway, c.pAway);
      close(r.pAway, 1 / (1 + Math.exp(-EDGE_SCALE * c.edge)));
    });
  }
});

describe("spread buckets (grid-aligned)", () => {
  // mirrors the bucketOf helpers used by SpreadWinPct / previews engine
  const bucket = (v: number, bs: number) => {
    const lo = Math.floor(v / bs + 1e-9) * bs;
    const frac = Math.abs(bs - Math.round(bs)) > 1e-9;
    const fmt = (x: number) => (frac ? x.toFixed(1) : String(Math.round(x)));
    return { label: `${fmt(lo)} to ${fmt(lo + bs)}`, lo };
  };
  for (const c of golden.spreadBuckets) {
    it(`${c.value} @ ${c.binSize}`, () => {
      const b = bucket(c.value, c.binSize);
      expect(b.label).toBe(c.label);
      close(b.lo, c.lo);
    });
  }
});

describe("gameId", () => {
  it("parses valid ids", () => {
    expect(parseGameId("2024_05_DAL_SF")).toEqual({ season: 2024, week: 5, away: "DAL", home: "SF" });
    expect(opponentLabel("2024_05_DAL_SF", "DAL")).toBe("@SF");
    expect(opponentLabel("2024_05_DAL_SF", "SF")).toBe("DAL");
  });
  it("rejects malformed ids (deviation #2)", () => {
    expect(parseGameId("garbage")).toBeNull();
    expect(opponentLabel("garbage", "SF")).toBe("—");
    expect(parseGameId(null)).toBeNull();
  });
});

describe("ranks helpers", () => {
  it("squashRatio compresses toward 0.5", () => {
    close(squashRatio(1), 0.75);
    close(squashRatio(0), 0.25);
    close(squashRatio(0.5), 0.5);
  });
  for (const c of golden.ranks) {
    it(`off=${c.offRank} def=${c.defAllowedRank}`, () => {
      expect(mismatchScore(c.offRank, c.defAllowedRank)).toBe(c.score);
      expect(mismatchEdge(c.offRank, c.defAllowedRank, c.maxRank)).toBe(c.edge);
    });
  }
});
